[project]
name = "restapp"
version = "0.1.0"
description = "Practise Task: REST API application for completing generative AI tasks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.119.1",
    "openai>=2.6.0",
    "ruff>=0.14.1",
]
